# Lab 4 - Reinforcement Learning

## Read details of the environment & model from a text file
Read: 

- Width, Height
- Noise: probability of not going in the intended direction (then divided by two for two unintentional neighbor directions)
- Immediate rewards of non-goal states
- Terminal (goal) states: their locations and rewards
- Internal Walls: locations

Create the transition matrix (T) and the Rewards matrix according to above details.

"grid1.txt" corresponds to the example in AIMA and the lecture slides. You can double-check various results there.

Python style comments in grid1.txt are just comments, can be ignored/deleted.

<div class='alert alert-block alert-success' style="font-weight:bolder">

### Task1
    
We ask you to create two more grids (files) of moderate size and with at least one internal wall. And perform the analysis described below on these three grids.
    
</div>

In [1]:
import numpy as np

# Enter number of grid : grid1, grid2, grid3
file1 = open('grid1.txt', 'r')

(W, H) = [t(s) for t, s in zip((int, int), file1.readline().split())]
noise = [t(s) for t, s in zip((float, str), file1.readline().split())][0]
immediate_rewards = [t(s) for t, s in zip((float, str), file1.readline().split())][0]
N = W * H  #total number of states
NA = 4  #number of actions
T = np.zeros((N, N, NA))  #state transition probabilities
Directions = np.array(['L', 'R', 'U', 'D'])
Rewards = np.zeros((N, 1)) + immediate_rewards  #immediate rewards
Terminals = np.zeros((N, 1))  #terminal states
Walls = np.zeros((N, 1))  #(internal) wall states
prob1 = 1 - noise
prob2 = noise / 2
while True:
    line = file1.readline()
    if not line:
        break
    if line.find('T') != -1:
        (_, x, y, r) = [t(s) for t, s in zip((str, int, int, float), line.split())]
        Terminals[y * W + x] = 1
        Rewards[y * W + x] = r
    if line.find('W') != -1:
        (_, x, y) = [t(s) for t, s in zip((str, int, int), line.split())]
        Walls[y * W + x] = 1
file1.close()
for i in range(W):
    for j in range(H):
        if i + 1 < W and Walls[j * W + i + 1] == 0:  #not wall on the right
            T[j * W + i, j * W + i + 1, 1] += prob1
            T[j * W + i, j * W + i + 1, 2] += prob2
            T[j * W + i, j * W + i + 1, 3] += prob2
        else:
            T[j * W + i, j * W + i, 1] += prob1
            T[j * W + i, j * W + i, 2] += prob2
            T[j * W + i, j * W + i, 3] += prob2
        if i - 1 >= 0 and Walls[j * W + i - 1] == 0:  #not wall on the left
            T[j * W + i, j * W + i - 1, 0] += prob1
            T[j * W + i, j * W + i - 1, 2] += prob2
            T[j * W + i, j * W + i - 1, 3] += prob2
        else:
            T[j * W + i, j * W + i, 0] += prob1
            T[j * W + i, j * W + i, 2] += prob2
            T[j * W + i, j * W + i, 3] += prob2
        if j + 1 < H and Walls[(j + 1) * W + i] == 0:  #not wall below
            T[j * W + i, (j + 1) * W + i, 3] += prob1
            T[j * W + i, (j + 1) * W + i, 0] += prob2
            T[j * W + i, (j + 1) * W + i, 1] += prob2
        else:
            T[j * W + i, j * W + i, 3] += prob1
            T[j * W + i, j * W + i, 0] += prob2
            T[j * W + i, j * W + i, 1] += prob2
        if j - 1 >= 0 and Walls[(j - 1) * W + i] == 0:  #not wall above
            T[j * W + i, (j - 1) * W + i, 2] += prob1
            T[j * W + i, (j - 1) * W + i, 0] += prob2
            T[j * W + i, (j - 1) * W + i, 1] += prob2
        else:
            T[j * W + i, j * W + i, 2] += prob1
            T[j * W + i, j * W + i, 0] += prob2
            T[j * W + i, j * W + i, 1] += prob2

print(T)

[[[0.9 0.1 0.9 0.1]
  [0.  0.8 0.1 0.1]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.1 0.1 0.  0.8]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]]

 [[0.8 0.  0.1 0.1]
  [0.2 0.2 0.8 0.8]
  [0.  0.8 0.1 0.1]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]]

 [[0.  0.  0.  0. ]
  [0.8 0.  0.1 0.1]
  [0.1 0.1 0.8 0. ]
  [0.  0.8 0.1 0.1]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.1 0.1 0.  0.8]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]]

 [[0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.8 0.  0.1 0.1]
  [0.1 0.9 0.9 0.1]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.1 0.1 0.  0.8]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  0.  0. ]]

 [[0.1 0.1 0.8 0. ]
  [0.  0.  0

<div class='alert alert-block alert-success' style="font-weight:bolder">

## Task 2 - Implement functions

### Task 2a - Value and Policy iteration
Value iteration is provided, implement policy iteration

### Task 2b - TD-Learning and Q-Learning
Q-Learning is implemented, implement TD-Learning
    
</div>

In [6]:
import numpy as np


def value_iteration(gamma, T, Rewards, Terminals, Walls):
    N, NA = T.shape[0], T.shape[2]
    V = np.zeros((N, 1))
    Policy = np.zeros((N, 1))
    iterations = 0
    while True:
        iterations += 1

        V_old = np.copy(V)
        for s in range(N):
            if Walls[s] == 1: continue
            if Terminals[s] == 1:
                V[s] = Rewards[s]
                continue
            Q = np.zeros((NA, 1))
            for a in range(NA):
                Q[a] = Rewards[s] + gamma * np.dot(T[s, :, a], V)
            V[s] = np.max(Q)
            Policy[s] = np.argmax(Q)
        if np.sum(np.abs(V - V_old)) < 1e-10:
            break
    print("Value Iteration converged in", iterations, "iterations.")
    return V, Policy


def policy_iteration(gamma, T, Rewards, Terminals, Walls):
    S, NA = T.shape[0], T.shape[2]
    V = np.zeros((N, 1))
    Policy = np.zeros((N, 1))
    iterations = 0

    while True:
        iterations += 1
        policy_stable = True
        b = Policy.copy()

        # Policy Evaluation
        while True:
            delta = 0
            for s in range(S):

                if Terminals[s] == 1:
                    V[s] = Rewards[s]
                    continue
                v = V[s].copy()
                pi = int(Policy[s])
                V[s] = Rewards[s] + gamma * np.dot(T[s, :, pi], V)
                delta = max(delta, np.abs(v - V[s]))
            if delta < 1e-1:
                break

        # Policy Iteration
        for s in range(S):
            if Terminals[s] == 1:
                V[s] = Rewards[s]
                continue
            Q = np.zeros((NA, 1))

            for a in range(NA):
                Q[a] = Rewards[s] + gamma * np.dot(T[s, :, a], V)
            Policy[s] = np.argmax(Q)

            if b[s] != Policy[s]:
                policy_stable = False
        if policy_stable:
            break
    print("Policy Iteration converged in", iterations, "iterations.")
    return V, Policy


def Q_learning(N_episodes, epsilon, alpha, gamma, T, Rewards, Terminals, Walls):
    N, NA = T.shape[0], T.shape[2]
    Q = np.zeros((N, NA))
    for e in range(N_episodes):
        s = int(np.floor(np.random.uniform(0, N - 1)))
        while Terminals[s] == 1 or Walls[s] == 1:
            s = int(np.floor(np.random.uniform(0, N - 1)))
        while Terminals[s] == 0:
            u = np.random.uniform(0, 1)
            if u < epsilon:
                a = int(np.floor(np.random.uniform(0, NA)))
            else:
                a = np.argmax(Q[s, :])
            u = np.random.uniform(0, 1)
            s1 = np.argmax(u < np.cumsum(T[s, :, a]))
            Q[s, a] += alpha * (Rewards[s1] + gamma * np.max(Q[s1, :]) - Q[s, a])
            s = s1
        epsilon = epsilon * 0.9999  # Modify here for other annealing regimes
        alpha = alpha * 0.9999  # Modify here for other annealing regimes
    V = np.max(Q, axis=1)
    V = V[:, None]
    V[Terminals == 1] = Rewards[Terminals == 1]
    Policy = np.array(np.argmax(Q, axis=1)).reshape((N, 1))
    return V, Policy


def TD_learning(N_episodes, alpha, gamma, T, Rewards, Terminals, Walls):
    N, NA = T.shape[0], T.shape[2]
    V = np.zeros((N, 1))
    Policy = np.zeros((N, 1))
    for episode in range(N_episodes):
        s = int(np.floor(np.random.uniform(0, N - 1)))
        while Terminals[s] == 1 or Walls[s] == 1:
            s = int(np.floor(np.random.uniform(0, N - 1)))
        while Terminals[s] == 0:
            Q = np.zeros((NA, 1))
            for a in range(NA):
                Q[a] = Rewards[s] + gamma * np.dot(T[s, :, a], V)
            a = np.argmax(Q)
            u = np.random.uniform(0, 1)
            s1 = np.argmax(u < np.cumsum(T[s, :, a]))
            V[s] += alpha * (Rewards[s1] + gamma * V[s1] - V[s])
            Policy[s] = a
            s = s1
            alpha = alpha * 0.9999

    V[Terminals == 1] = Rewards[Terminals == 1]
    return V, Policy


<div class='alert alert-block alert-success' style="font-weight:bolder">
    
## Task 3 - Experiments

For the three grids you have, perform the following analysis and include them in your report,.

- Compare value and policy iterations in terms of convergence time. Relate it to computational complexity, current implementation and number of iterations needed.

- How are optimal policies change with immediate reward values? Show some examples (similar to Figure 17.2b in AIMA)

- Compare TD-Learning and Q-Learning results with each other. Also with value and policy iterations. Remember that value and policy iteration solve Markov Decision Processes where we know the model (T and Rewards). TD-Learning and Q-Learning are (passive and active, respectively) Reinforcement Learning methods that don't have the model but use data from simulations. Data are simulated from the model we know, but the model is not used n TD or Q-Learning.

- What are the effects of epsilon and alpha values and how they are modified?

- What is the effect of number of episodes?
    
</div>

In [7]:
gamma = 1
alpha = 0.9
epsilon = 0.5
N_episodes = 20000

#Value iteration
V_VI, Policy_VI = value_iteration(gamma, T, Rewards, Terminals, Walls)

#Policy iteration
V_PI, Policy_PI = policy_iteration(gamma, T, Rewards, Terminals, Walls)

#Q-Learning
V_Q, Policy_Q = Q_learning(N_episodes, epsilon, alpha, gamma, T, Rewards, Terminals, Walls)

#TD-Learning
V_TD, Policy_TD = TD_learning(N_episodes, alpha, gamma, T, Rewards, Terminals, Walls)

print("Value Iteration:\n", V_VI.reshape((H, W)))
maze = Directions[Policy_VI.astype(int)]
maze[Walls == 1] = 'W'
maze[Terminals == 1] = 'G'
print("Maze reshape:\n", maze.reshape((H, W)))
#
print("\nPolicy Iteration:\n", V_PI.reshape((H, W)))
maze = Directions[Policy_PI.astype(int)]
maze[Walls == 1] = 'W'
maze[Terminals == 1] = 'G'
print("Maze reshape:\n", maze.reshape((H, W)))
#
print("\nQ Learning:\n", V_Q.reshape((H, W)))
maze_Q = Directions[Policy_Q.astype(int)]
maze_Q[Walls == 1] = 'W'
maze_Q[Terminals == 1] = 'G'
print("Maze reshape:\n", maze_Q.reshape((H, W)))
#
print("\nTD Learning:\n", V_TD.reshape((H, W)))
maze_TD = Directions[Policy_TD.astype(int)]
maze_TD[Walls == 1] = 'W'
maze_TD[Terminals == 1] = 'G'
print("Maze reshape:\n", maze_TD.reshape((H, W)))


Value Iteration converged in 29 iterations.
Policy Iteration converged in 6 iterations.


/var/folders/gq/2nwzl2_x23bg470lkxq503g40000gp/T/ipykernel_83720/1054134247.py:49: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  pi = int(Policy[s])
/var/folders/gq/2nwzl2_x23bg470lkxq503g40000gp/T/ipykernel_83720/1054134247.py:89: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Q[s, a] += alpha * (Rewards[s1] + gamma * np.max(Q[s1, :]) - Q[s, a])


Value Iteration:
 [[ 0.81155822  0.86780822  0.91780822  1.        ]
 [ 0.76155822  0.          0.66027397 -1.        ]
 [ 0.70530822  0.65530822  0.61141553  0.38792491]]
Maze reshape:
 [['R' 'R' 'R' 'G']
 ['U' 'W' 'U' 'G']
 ['U' 'L' 'L' 'L']]

Policy Iteration:
 [[ 0.81086593  0.86780445  0.917808    1.        ]
 [ 0.76007897  0.79627873  0.66027367 -1.        ]
 [ 0.689108    0.61655665  0.58556575  0.36414374]]
Maze reshape:
 [['R' 'R' 'R' 'G']
 ['U' 'W' 'U' 'G']
 ['U' 'L' 'U' 'L']]

Q Learning:
 [[ 0.88661998  0.94603854  0.99689938  1.        ]
 [ 0.81379897  0.          0.63040612 -1.        ]
 [ 0.75814308  0.69969592  0.66335169  0.54054948]]
Maze reshape:
 [['R' 'R' 'R' 'G']
 ['U' 'W' 'L' 'G']
 ['U' 'L' 'L' 'L']]

TD Learning:
 [[ 0.42489962  0.52568713  0.57742369  1.        ]
 [ 0.30058905  0.          0.26359621 -1.        ]
 [ 0.11421557 -0.02617961 -0.00857958 -0.88289877]]
Maze reshape:
 [['R' 'R' 'U' 'G']
 ['U' 'W' 'U' 'G']
 ['U' 'L' 'U' 'U']]


<div class='alert alert-block alert-success' style="font-weight:bolder">

## Task 4 (extra credit) - What if diagonal moves were possible?

Repeat the experiments in one of these settings. You don't have to stick to the code provided here. But, you can only use Numpy (and matplotlib).

You should decide on how to distribute the noise associated with actions across (next) states. For example, in the scenario above we have probability of going Up with the Up action is 1-noise. The probability of going Left with the Up action is noise/2. The same for going Right.
    
</div>

In [1]:
import numpy as np

def read_grid(file_path):
    file1 = open(file_path, 'r')

    W, H = [t(s) for t, s in zip((int, int), file1.readline().split())]
    noise = [t(s) for t, s in zip((float, str), file1.readline().split())][0]
    immediate_rewards = [t(s) for t, s in zip((float, str), file1.readline().split())][0]
    N = W * H  # total number of states
    NA = 8  # number of actions (including diagonals)
    T = np.zeros((N, N, NA))  # state transition probabilities
    Directions = np.array(['L', 'R', 'U', 'D', 'UL', 'UR', 'DL', 'DR'])
    Rewards = np.zeros((N, 1)) + immediate_rewards  # immediate rewards
    Terminals = np.zeros((N, 1))  # terminal states
    Walls = np.zeros((N, 1))  # (internal) wall states
    prob1 = 1 - noise
    prob2 = noise / 2

    while True:
        line = file1.readline()
        if not line:
            break
        if line.find('T') != -1:
            (_, x, y, r) = [t(s) for t, s in zip((str, int, int, float), line.split())]
            Terminals[y * W + x] = 1
            Rewards[y * W + x] = r
        if line.find('W') != -1:
            (_, x, y) = [t(s) for t, s in zip((str, int, int), line.split())]
            Walls[y * W + x] = 1

    file1.close()

    for i in range(W):
        for j in range(H):
            # Actions: 0-L, 1-R, 2-U, 3-D, 4-UL, 5-UR, 6-DL, 7-DR
            if i + 1 < W and Walls[j * W + i + 1] == 0:  # not wall on the right
                T[j * W + i, j * W + i + 1, 1] += prob1
                T[j * W + i, j * W + i + 1, 2] += prob2
                T[j * W + i, j * W + i + 1, 3] += prob2
                T[j * W + i, j * W + i + 1, 5] += prob2 / 2  # UR
                T[j * W + i, j * W + i + 1, 7] += prob2 / 2  # DR
            else:
                T[j * W + i, j * W + i, 1] += prob1
                T[j * W + i, j * W + i, 2] += prob2
                T[j * W + i, j * W + i, 3] += prob2
                T[j * W + i, j * W + i, 5] += prob2 / 2  # UR
                T[j * W + i, j * W + i, 7] += prob2 / 2  # DR

            if i - 1 >= 0 and Walls[j * W + i - 1] == 0:  # not wall on the left
                T[j * W + i, j * W + i - 1, 0] += prob1
                T[j * W + i, j * W + i - 1, 2] += prob2
                T[j * W + i, j * W + i - 1, 3] += prob2
                T[j * W + i, j * W + i - 1, 4] += prob2 / 2  # UL
                T[j * W + i, j * W + i - 1, 6] += prob2 / 2  # DL
            else:
                T[j * W + i, j * W + i, 0] += prob1
                T[j * W + i, j * W + i, 2] += prob2
                T[j * W + i, j * W + i, 3] += prob2
                T[j * W + i, j * W + i, 4] += prob2 / 2  # UL
                T[j * W + i, j * W + i, 6] += prob2 / 2  # DL

            if j + 1 < H and Walls[(j + 1) * W + i] == 0:  # not wall below
                T[j * W + i, (j + 1) * W + i, 3] += prob1
                T[j * W + i, (j + 1) * W + i, 0] += prob2
                T[j * W + i, (j + 1) * W + i, 1] += prob2
                T[j * W + i, (j + 1) * W + i, 6] += prob2 / 2  # DL
                T[j * W + i, (j + 1) * W + i, 7] += prob2 / 2  # DR
            else:
                T[j * W + i, j * W + i, 3] += prob1
                T[j * W + i, j * W + i, 0] += prob2
                T[j * W + i, j * W + i, 1] += prob2
                T[j * W + i, j * W + i, 6] += prob2 / 2  # DL
                T[j * W + i, j * W + i, 7] += prob2 / 2  # DR

            if i + 1 < W and j - 1 >= 0 and Walls[(j - 1) * W + i + 1] == 0:  # not wall on the down-right
                T[j * W + i, (j - 1) * W + i + 1, 5] += prob2 / 2  # Up-Right
                T[j * W + i, (j - 1) * W + i + 1, 7] += prob2 / 2  # Down-Right

            if i - 1 >= 0 and j - 1 >= 0 and Walls[(j - 1) * W + i - 1] == 0:  # not wall on the down-left
                T[j * W + i, (j - 1) * W + i - 1, 4] += prob2 / 2  # Up-Left
                T[j * W + i, (j - 1) * W + i - 1, 6] += prob2 / 2  # Down-Left

    return T, Rewards, Terminals, Walls, Directions, W, H

# Example usage
file_path = 'grid1.txt'
T, Rewards, Terminals, Walls, Directions, W, H = read_grid(file_path)

print("Transition Probabilities:")
print(T)
print("\nRewards:")
print(Rewards)
print("\nTerminal States:")
print(Terminals)
print("\nWalls:")
print(Walls)
print("\nDirections:")
print(Directions)
print("\nGrid Dimensions (W, H):", W, H)


Transition Probabilities:
[[[0.8  0.   0.1  ... 0.   0.05 0.  ]
  [0.   0.8  0.1  ... 0.05 0.   0.05]
  [0.   0.   0.   ... 0.   0.   0.  ]
  ...
  [0.   0.   0.   ... 0.   0.   0.  ]
  [0.   0.   0.   ... 0.   0.   0.  ]
  [0.   0.   0.   ... 0.   0.   0.  ]]

 [[0.8  0.   0.1  ... 0.   0.05 0.  ]
  [0.1  0.1  0.   ... 0.   0.05 0.05]
  [0.   0.8  0.1  ... 0.05 0.   0.05]
  ...
  [0.   0.   0.   ... 0.   0.   0.  ]
  [0.   0.   0.   ... 0.   0.   0.  ]
  [0.   0.   0.   ... 0.   0.   0.  ]]

 [[0.   0.   0.   ... 0.   0.   0.  ]
  [0.8  0.   0.1  ... 0.   0.05 0.  ]
  [0.   0.   0.   ... 0.   0.   0.  ]
  ...
  [0.   0.   0.   ... 0.   0.   0.  ]
  [0.   0.   0.   ... 0.   0.   0.  ]
  [0.   0.   0.   ... 0.   0.   0.  ]]

 ...

 [[0.   0.   0.   ... 0.   0.   0.  ]
  [0.   0.   0.   ... 0.   0.   0.  ]
  [0.   0.   0.   ... 0.   0.   0.  ]
  ...
  [0.1  0.1  0.   ... 0.   0.05 0.05]
  [0.   0.8  0.1  ... 0.05 0.   0.05]
  [0.   0.   0.   ... 0.   0.   0.  ]]

 [[0.   0.   0.   ... 0.